import { expect, test, request } from "@playwright/test";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import type { OrderDetail, OrderFields } from "../src/api/orders";

const fixture = JSON.parse(readFileSync(new URL("./.real-api-fixture.json", import.meta.url), "utf8")) as {
  origins: { admin: string; b2b: string }; root: { username: string; password: string };
  orderUser: { username: string; temporaryPassword: string };
};
const API = "http://127.0.0.1:8789";
const snapshot = () => JSON.parse(execFileSync("php", [fileURLToPath(new URL("./db-snapshot.php", import.meta.url))], { encoding: "utf8", env: process.env })) as Record<string, unknown>;
const production = () => Object.fromEntries(Object.entries(snapshot()).filter(([key]) => key !== "b2b_companies"));

test("sales identity completes Classic Order lifecycle through real API without touching production", async ({ page }) => {
  const before = production(), routes: string[] = [];
  page.on("request", r => { if (r.url().startsWith(API)) routes.push(new URL(r.url()).pathname); });
  page.on("pageerror", error => { throw error; });
  const admin = await request.newContext();
  const auth = await admin.post(API + "/auth/login", { headers: { Origin: fixture.origins.admin }, data: fixture.root });
  expect(auth.status()).toBe(200);
  const csrf = (await auth.json()).csrfToken as string;
  const headers = () => ({ Origin: fixture.origins.admin, "X-CSRF-Token": csrf, "Idempotency-Key": crypto.randomUUID() });
  const companyFields = { legalName: "Classic Client SRL", displayName: null, countryCode: "RO", taxIdentifier: "9834567",
    vatNumber: null, registrationNumber: "J40/2/2026", website: null, internalNotes: null };
  const created = await admin.post(API + "/b2b/companies", { headers: headers(), data: companyFields });
  expect(created.status()).toBe(201);
  const companyId = (await created.json()).companyId as string;

  await page.goto("/");
  await page.getByLabel("Nume utilizator").fill(fixture.orderUser.username);
  await page.getByLabel("Parolă", { exact: true }).fill(fixture.orderUser.temporaryPassword);
  await page.getByRole("button", { name: "Intrare în cont" }).click();
  await expect(page.getByRole("heading", { name: "Schimbați parola" })).toBeVisible();
  await page.getByLabel("Parola actuală").fill(fixture.orderUser.temporaryPassword);
  await page.getByLabel("Parola nouă", { exact: true }).fill("classic orders e2e permanent 2026");
  await page.getByLabel("Confirmați parola nouă").fill("classic orders e2e permanent 2026");
  await page.getByRole("button", { name: "Salvează parola" }).click();
  await expect(page.getByRole("heading", { name: "Bun venit, Ana Comenzi." })).toBeVisible();
  await page.goto(`/comenzi/noua?companyId=${companyId}`);
  await page.getByRole("button", { name: "Adaugă linie" }).click();
  await page.getByLabel("Cod produs 1", { exact: true }).fill("C-REAL");
  await page.getByLabel("Cantitate 1", { exact: true }).fill("4");
  await page.getByLabel("Unitate de facturare 1").selectOption("meter");
  await page.getByLabel("Metri total 1").fill("13,5");
  await page.getByLabel("Preț unitar net 1").fill("10,00");
  await page.getByLabel("TVA % 1").fill("19");
  await expect(page.getByTestId("order-totals")).toContainText("160.65 RON");
  await page.getByLabel("Cod produs 1", { exact: true }).press("Control+s");
  await expect(page.getByRole("heading", { level: 1 })).toHaveText(/^B2B-ORD-\d{6}$/);
  const orderUrl = page.url(), id = orderUrl.split("/").at(-1)!;
  const load = async () => (await (await admin.get(`${API}/b2b/orders/${id}`)).json()) as OrderDetail;
  let detail = await load();
  expect(detail.order.lines[0].quantity).toBe(4);
  expect(detail.order.lines[0].meters).toBe("13.500");
  expect(detail.order.calculation.totals).toEqual({ net: "135.00", vat: "25.65", gross: "160.65" });
  const originalLineId = detail.order.lines[0].id;
  await page.getByRole("button", { name: "Duplică linia 1", exact: true }).click();
  await expect(page.locator(".order-line")).toHaveCount(2);
  await page.getByRole("button", { name: "Mută în sus 2", exact: true }).click();
  await page.getByRole("button", { name: "Șterge linia 1", exact: true }).click();
  await expect(page.locator(".order-line")).toHaveCount(1);
  await page.getByLabel("Cod produs 1", { exact: true }).press("Control+s");
  await expect(page.getByRole("button", { name: "Salvează ciorna", exact: true })).toBeDisabled();
  detail = await load(); expect(detail.order.lines[0].id).toBe(originalLineId);

  const fields: OrderFields = { companyId, currencyCode: detail.order.currencyCode, contactId: null, billingAddressId: null, deliveryAddressId: null,
    customerReference: "Concurrent reference", notes: null, productionNotes: null, lines: detail.order.lines };
  const concurrent = await admin.put(`${API}/b2b/orders/${id}`, { headers: headers(), data: { ...fields, expectedVersion: detail.order.version } });
  expect(concurrent.status()).toBe(200);
  await page.getByLabel("Referință client").fill("Local preserved reference");
  await page.getByRole("button", { name: "Salvează ciorna", exact: true }).click();
  await expect(page.getByLabel("Referință client")).toHaveValue("Local preserved reference");
  await page.getByRole("button", { name: "Vezi versiunea actuală" }).click();
  await page.getByRole("button", { name: "Păstrează datele mele pe versiunea actuală" }).click();
  await page.getByRole("button", { name: "Salvează ciorna", exact: true }).click();
  await expect(page.getByRole("button", { name: "Finalizează", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Finalizează", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("160.65 RON");
  await page.getByRole("button", { name: "Confirmă finalizarea" }).click();
  await expect(page.getByLabel("Cod produs 1", { exact: true })).toBeDisabled();
  const updateCompany = await admin.put(`${API}/b2b/companies/${companyId}`, { headers: headers(), data: { ...companyFields, legalName: "Changed live company", expectedVersion: 1 } });
  expect(updateCompany.status()).toBe(200);
  await page.reload();
  await expect(page.locator(".order-snapshot").first()).toContainText("Classic Client SRL");
  await page.getByRole("button", { name: "Anulează comanda", exact: true }).click();
  await page.getByRole("button", { name: "Confirmă anularea" }).click();
  await expect(page.locator(".order-heading-meta")).toContainText("Anulată");
  await page.getByRole("button", { name: "Duplică în ciornă" }).click();
  await expect(page).not.toHaveURL(orderUrl);
  await expect(page.getByLabel("Cod produs 1", { exact: true })).toBeEnabled();
  await expect(page.locator(".order-snapshot").first()).toContainText("Changed live company");
  await page.getByRole("button", { name: "TR — Türkçe" }).click();
  await expect(page.getByRole("button", { name: "Taslağı kaydet", exact: true })).toBeVisible();
  await page.getByRole("navigation").getByRole("link", { name: "Şirketler", exact: true }).click();
  await page.getByRole("link", { name: "Changed live company" }).click();
  await expect(page.getByRole("heading", { name: "Sipariş geçmişi" })).toBeVisible();
  await expect(page.locator(".order-list-item")).toHaveCount(2);
  expect(production()).toEqual(before);
  expect(routes.every(path => /^\/(auth\/|b2b\/)/.test(path))).toBe(true);
  expect(await page.evaluate(() => [sessionStorage.length, Object.keys(localStorage)])).toEqual([0, ["arasya.b2b.locale"]]);
  await admin.dispose();
});
