import { plural } from '../i18n/plural';
export const ordersRo = {
 lineCount:(n:number)=>plural('ro',n,{one:'{n} produs',few:'{n} produse',other:'{n} de produse'}),
 customerReference:'Referință client',productionNotes:'Instrucțiuni pentru producție',cancelled:'Anulată',cancelOrder:'Anulează comanda',
 confirmCancel:'Confirmă anularea',cancelQuestion:'Anulați această comandă?',cancelHint:'Comanda și istoricul sunt păstrate. Anularea este definitivă.',
 freezeHint:'Finalizarea blochează compania, moneda, produsele, dimensiunile și toate datele comerciale.',
 productionBoundary:'Finalizarea nu trimite comanda în producție; trimiterea necesită o acțiune separată.',snapshotHint:'Date istorice salvate la finalizare; modificările ulterioare ale companiei nu schimbă această comandă.',
 workstation:'Comandă en-gros · intrare rapidă',unsavedState:'Modificări nesalvate',firstLine:'Adăugați prima linie pentru a începe comanda.',
 keyboardHint:'Tab / Enter: câmpul următor · Ctrl / Cmd + S: salvare · Alt + Enter: linie nouă',
 moveUp:'Mută în sus',moveDown:'Mută în jos',line_created:'Linie adăugată',line_updated:'Linie actualizată',line_duplicated:'Linie duplicată',
 line_removed:'Linie eliminată',lines_reordered:'Ordine linii modificată',order_cancelled:'Comandă anulată',from:'De la',to:'Până la',
 title:'Comenzi',newOrder:'Comandă nouă',noView:'Nu aveți permisiunea de a vedea comenzile.',noCreate:'Crearea necesită permisiunea pentru comenzi și vizualizarea companiilor.',search:'Căutare',statusLabel:'Stare',all:'Toate',draft:'Ciornă',finalized:'Finalizată',company:'Companie',companySearch:'Caută companie activă',selectCompany:'Selectați compania',currency:'Monedă',currencyHint:'Pentru a schimba moneda, ștergeți prețurile și salvați mai întâi ciorna.',contact:'Persoană de contact',billing:'Adresă de facturare',delivery:'Adresă de livrare',none:'Neselectat',unavailableSelection:'Înregistrare selectată indisponibilă',notes:'Note comandă',lines:'Produse',addLine:'Adaugă linie',duplicateLine:'Duplică linia',removeLine:'Șterge linia',details:'Măsurători și detalii',productCode:'Cod produs',productName:'Denumire produs',variant:'Variantă',color:'Culoare',kind:'Tip produs',curtain:'Perdea',drapery:'Draperie',other:'Altele',width:'Lățime (cm)',height:'Înălțime (cm)',quantity:'Cantitate',meters:'Metri total',pricingUnit:'Unitate de facturare',piece:'Bucată',meter:'Metru',unitPriceNet:'Preț unitar net',discountPercent:'Reducere %',vatPercent:'TVA %',lineNotes:'Note linie',net:'Net',vat:'TVA',gross:'Total',baseNet:'Bază netă',discountNet:'Reducere netă',pending:'Calcul în curs…',incomplete:'Total incomplet — completați codurile, prețurile și TVA.',save:'Salvează ciorna',saved:'Ciorna a fost salvată.',createdNoView:'Ciorna a fost creată. Nu aveți permisiunea de a vedea detaliile.',finalize:'Finalizează',finalizeHint:'Salvați o ciornă completă înainte de finalizare.',confirmFinalize:'Confirmă finalizarea',finalizeQuestion:'Finalizați această comandă? Datele comerciale devin definitive.',cancel:'Anulează',duplicate:'Duplică în ciornă',history:'Istoric comenzi',activity:'Activitate',empty:'Nicio comandă corespunde filtrelor.',more:'Încarcă mai multe',loading:'Se încarcă…',conflict:'Comanda a fost modificată între timp. Datele introduse sunt păstrate.',viewCurrent:'Vezi versiunea actuală',current:'Versiunea actuală de pe server',keepMine:'Păstrează datele mele pe versiunea actuală',useServer:'Folosește versiunea actuală',unsaved:'Aveți modificări nesalvate. Părăsiți pagina?',fieldInvalid:'Valoare nevalidă. Verificați formatul și limitele.',fieldRequired:'Completați acest câmp.',fieldInactive:'Înregistrarea selectată nu este activă.',fieldLong:'Textul depășește limita permisă.',source:'Comandă sursă',created:'Creată',updated:'Actualizată',actor:'Autor',version:'Versiune',order_created:'Comandă creată',order_updated:'Ciornă actualizată',order_finalized:'Comandă finalizată',order_duplicated:'Comandă duplicată',unknownActivity:'Comandă modificată',changedFields:'Câmpuri modificate',reference:'Referință',measureHint:'Metrii reprezintă totalul liniei. Dimensiunile nu determină facturarea.',readOnly:'Date comerciale definitive',
};
export const ordersTr:typeof ordersRo = {
 lineCount:(n:number)=>plural('tr',n,{other:'{n} ürün'}),
 customerReference:'Müşteri referansı',productionNotes:'Üretim talimatları',cancelled:'İptal edildi',cancelOrder:'Siparişi iptal et',
 confirmCancel:'İptali onayla',cancelQuestion:'Siparişi iptal ediyor musunuz?',cancelHint:'Sipariş ve geçmişi korunur. İptal geri alınamaz.',
 freezeHint:'Kesinleştirme şirketi, para birimini, ürünleri, ölçüleri ve tüm ticari bilgileri kilitler.',
 productionBoundary:'Kesinleştirme siparişi üretime göndermez; gönderim ayrı bir işlem gerektirir.',snapshotHint:'Kesinleştirmede kaydedilen tarihsel bilgiler; sonraki şirket değişiklikleri bu siparişi değiştirmez.',
 workstation:'Toptan sipariş · hızlı giriş',unsavedState:'Kaydedilmemiş değişiklikler',firstLine:'Siparişi başlatmak için ilk satırı ekleyin.',
 keyboardHint:'Tab / Enter: sonraki alan · Ctrl / Cmd + S: kaydet · Alt + Enter: yeni satır',
 moveUp:'Yukarı taşı',moveDown:'Aşağı taşı',line_created:'Satır eklendi',line_updated:'Satır güncellendi',line_duplicated:'Satır kopyalandı',
 line_removed:'Satır kaldırıldı',lines_reordered:'Satır sırası değiştirildi',order_cancelled:'Sipariş iptal edildi',from:'Başlangıç',to:'Bitiş',
 title:'Siparişler',newOrder:'Yeni sipariş',noView:'Siparişleri görüntüleme yetkiniz yok.',noCreate:'Oluşturmak için sipariş oluşturma ve şirket görüntüleme yetkisi gerekir.',search:'Arama',statusLabel:'Durum',all:'Tümü',draft:'Taslak',finalized:'Kesinleştirildi',company:'Şirket',companySearch:'Aktif şirket ara',selectCompany:'Şirket seçin',currency:'Para birimi',currencyHint:'Para birimini değiştirmek için fiyatları temizleyip önce taslağı kaydedin.',contact:'İletişim kişisi',billing:'Fatura adresi',delivery:'Teslimat adresi',none:'Seçilmedi',unavailableSelection:'Seçili kayıt kullanılamıyor',notes:'Sipariş notları',lines:'Ürünler',addLine:'Satır ekle',duplicateLine:'Satırı kopyala',removeLine:'Satırı sil',details:'Ölçüler ve ayrıntılar',productCode:'Ürün kodu',productName:'Ürün adı',variant:'Varyant',color:'Renk',kind:'Ürün türü',curtain:'Tül',drapery:'Fon perde',other:'Diğer',width:'Genişlik (cm)',height:'Yükseklik (cm)',quantity:'Adet',meters:'Toplam metre',pricingUnit:'Faturalama birimi',piece:'Adet',meter:'Metre',unitPriceNet:'Net birim fiyat',discountPercent:'İndirim %',vatPercent:'KDV %',lineNotes:'Satır notları',net:'Net',vat:'KDV',gross:'Toplam',baseNet:'Net taban',discountNet:'Net indirim',pending:'Hesaplanıyor…',incomplete:'Toplam eksik — kodları, fiyatları ve KDV oranlarını tamamlayın.',save:'Taslağı kaydet',saved:'Taslak kaydedildi.',createdNoView:'Taslak oluşturuldu. Ayrıntıları görüntüleme yetkiniz yok.',finalize:'Kesinleştir',finalizeHint:'Kesinleştirmeden önce eksiksiz bir taslak kaydedin.',confirmFinalize:'Kesinleştirmeyi onayla',finalizeQuestion:'Siparişi kesinleştiriyor musunuz? Ticari bilgiler değiştirilemez hale gelir.',cancel:'Vazgeç',duplicate:'Taslak olarak kopyala',history:'Sipariş geçmişi',activity:'Etkinlik',empty:'Filtrelerle eşleşen sipariş yok.',more:'Daha fazla yükle',loading:'Yükleniyor…',conflict:'Sipariş başka biri tarafından değiştirildi. Girdiğiniz bilgiler korunuyor.',viewCurrent:'Güncel sürümü göster',current:'Sunucudaki güncel sürüm',keepMine:'Bilgilerimi güncel sürüm üzerinde koru',useServer:'Güncel sürümü kullan',unsaved:'Kaydedilmemiş değişiklikler var. Sayfadan ayrılsın mı?',fieldInvalid:'Geçersiz değer. Biçimi ve sınırları kontrol edin.',fieldRequired:'Bu alanı doldurun.',fieldInactive:'Seçili kayıt aktif değil.',fieldLong:'Metin izin verilen sınırı aşıyor.',source:'Kaynak sipariş',created:'Oluşturuldu',updated:'Güncellendi',actor:'Yazar',version:'Sürüm',order_created:'Sipariş oluşturuldu',order_updated:'Taslak güncellendi',order_finalized:'Sipariş kesinleştirildi',order_duplicated:'Sipariş kopyalandı',unknownActivity:'Sipariş değiştirildi',changedFields:'Değişen alanlar',reference:'Referans',measureHint:'Metreler satırın toplamıdır. Ölçüler faturalama miktarını belirlemez.',readOnly:'Kesinleşmiş ticari bilgiler',
};
